import './globals.css'
import { sans } from '@/app/fonts';

export const metadata = {
  title: 'Baby Line',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={sans.className}>{children}</body>
    </html>
  )
}
